--PRIMEIRO FAÇO UM SELECT NA TABELA TODA PARA IDENTIFICAR O CONTEÚDO
SELECT * 
	FROM CIDADES

--INICIO UMA TRANSAÇÃO PARA PODER CONFIRMAR AS ALTERAÇÕES QUE SERÃO REALIZADAS
BEGIN TRANSACTION;

UPDATE CIDADES
   SET 
	   ESTADO = 'SP'
 WHERE ESTADO = 'PR'


--APÓS O COMANDO DE UPDATE, CONFIRMO PARA SABER SE A ATUALIZAÇÃO OCORREU CONFORME ESPERADO
SELECT * 
	FROM CIDADES

--AQUI JÁ DEIXO OS COMANDOS DE COMMIT (CASO TENHA OCORRIDO COMO O PLANEJADO A ATUALIZAÇÃO)
--OU ROLLBACK, CASO TENHA OCORRIDO ALGO INESPERADO 

--COMMIT;
--ROLLBACK;