USE [sinqia]
GO

/****** Object:  View [dbo].[VW_CLIENTES]    Script Date: 14/03/2024 18:32:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[VW_CLIENTES] AS
SELECT [CLIENTES].[CODIGO_CLIENTE]
      ,[CLIENTES].[CGC_CPF_CLIENTE]
      ,[CLIENTES].[NOME]
      ,[CLIENTES].[TELEFONE]
      ,[CLIENTES].[E_MAIL]
      ,[CLIENTES].[CEP]
      ,[CLIENTES].[ENDERECO]
      ,[CLIENTES].[BAIRRO]
      ,[CLIENTES].[COMPLEMENTO]
      ,[CLIENTES].[CODIGO_CIDADE]
	  ,[CIDADES].[NOME] AS NOME_CIDADE
	  ,[CIDADES].[ESTADO]
  FROM [SINQIA].[DBO].[CLIENTES]
  INNER JOIN CIDADES ON CLIENTES.CODIGO_CIDADE = CIDADES.CODIGO_CIDADE

GO

